### ISSUE TITLE
`noSideEffect` not affected by `echo`

### ISSUE THREAD

**Issue by hasenj** [flaviut/nim-by-example#27]
I'm not sure why but it seems the `echo` statement does not cause errors in "pure" functions.

The example from http://nim-by-example.github.io/procs/ actually compiles with no issues

```
proc minus(x, y: int): int {. noSideEffect .} =
  echo x  # error: 'minus' can have side effects
  x - y
```

I don't know if this is a bug in Nim or the tutorial.

This code will successfully cause the compiler to complain:

```
var counter = 0
proc minus(x, y: int): int {. noSideEffect .} =
    counter.inc # error: 'minus' can have side effects
    x - y
```

**Comment by dom96** [comment]
I think this is a Nim bug. I submitted this on Nim's issue tracker.

**Comment by flaviut** [comment]
I'd rather leave this open, maybe it deserves a special mention.

**Comment by flaviut** [comment]
Nope: There is a special `debugEcho` which skip side effect checks though.
