### ISSUE TITLE
Immutablity of Sequences

### ISSUE THREAD

**Issue by ftsf** [flaviut/nim-by-example#39]
https://nim-by-example.github.io/seqs/

> While sequences are dynamically allocated, they are still immutable.

This seems to contradict with the example

```
var b = @[1, 2, 3]
b.add(4)
```

> will work without any problems

**Comment by flaviut** [comment]
```nim
var b = @[1, 2, 3]
b = @[1, 2, 3, 4]
```
is equivalent to that code. The sequence itself is not modified (well, I think it is, but that's an optimization), but the variable *is* modified.

**Comment by ftsf** [comment]
From the Nim Manual:
> Sequences are similar to arrays but of dynamic length which may change during runtime (like strings). 
> Sequences are implemented as growable arrays, allocating pieces of memory as items are added. 

This seems to directly contradict the immutable statement which is quite confusing.

**Comment by flaviut** [comment]
I'll go over that page and change it when I get back in town. Both
statements are kinda correct; it can definitely use some clarification.
