### ISSUE TITLE
Out of date example about procvar ?

### ISSUE THREAD

**Issue by k0pernicus** [flaviut/nim-by-example#51]
In chapter about First Class Functions, it seems that the behavior of the new compiler has changed to use `procvar`.
Actually,
```
proc greaterThan32(x: int): bool {.procvar.} = x > 32
echo powersOfTwo.filter(greaterThan32)
```
and
```
proc greaterThan32(x: int): bool = x > 32
echo powersOfTwo.filter(greaterThan32)
```
seem have the same behavior today.

**Comment by retsyo** [comment]
it is nice to code without {.procvar.}

**Comment by flaviut** [comment]
Thank you, fixed!
