### ISSUE TITLE
{.pure.} enum doesn't follow updated spec

### ISSUE THREAD

**Issue by timotheecour** [flaviut/nim-by-example#67]
https://nim-by-example.github.io/types/enums/
https://github.com/flaviut/nim-by-example/blob/master/content/content/types/enums.md

> The {.pure.} pragma that Colors has requires that all references to Colors's values be qualified

is now out of spec

the spec was updated here by @araq https://github.com/nim-lang/Nim/commit/2f7b979e384ff6cc750e123939401a72c3f59093 (see discussion here: https://github.com/nim-lang/Nim/issues/8066)

**Comment by flaviut** [comment]
Thank you for letting me know about this. I'll let the discussion continue on this issue and update the website whenever everyone figures out how this is supposed to work :)

**Comment by flaviut** [comment]
Fixed in ae512d7b432e6ad73d10ec288d1647f27236b9c2, thanks!
