### ISSUE TITLE
First Class Functions section

### ISSUE THREAD

**Issue by jabbalaci** [flaviut/nim-by-example#70]
First of all, thanks for the great tutorial.

I think the section https://nim-by-example.github.io/procvars/ could be improved. IMO this section is about lambda (anonymous) functions, thus the title is misleading, and the word "lambda" is not mentioned. 

Let's consider this line:

```nim
    echo powersOfTwo.filter(proc (x: int): bool = x > 32)
```

There is a simpler syntax for mapping and filtering with `mapIt` and `filterIt`. The line above could be written as:

```nim
    echo powersOfTwo.filterIt(it > 32)
```

Much simpler and beginner-frindlier.

**Comment by jabbalaci** [comment]
Since then I've found another simple version that should be mentioned too:

```nim
import sugar       # =>

echo numbers.filter(x => x > 32)
```

**Comment by flaviut** [comment]
`filterIt` and `mapIt` are not any specific syntax, they are just templates that re-write the expression in a certain way. They aren't really lambdas; you can't do `let foo = it+1`. I have added in a section about the sugar, good catch!

**Comment by jabbalaci** [comment]
Your solution could be simplified. There is a `map` in `sequtils`, no need to ship your own:

```nim
import strutils    # join
import sequtils    # map
import sugar       # =>

echo "foo".map(c => char(ord(c) + 1)).join()
```

As I'm learning Nim, an own implementation of `map` was interesting for me though.

**Comment by jabbalaci** [comment]
I didn't notice that. It would be great if you added some textual description of the used macros. For beginners it's not trivial.

**Comment by flaviut** [comment]
Done. Thanks for your feedback, it's always nice when I get feedback from people who don't already know the information.

**Comment by jabbalaci** [comment]
Thanks for the clarification!
