### ISSUE TITLE
Apparently an error

### ISSUE THREAD

**Issue by Kpjas** [flaviut/nim-by-example#89]
Absolute beginner.

https://nim-by-example.github.io/for_iterators/

for i in 0...5:
  echo i

Gives me an error

but

for i in 0..5:
  echo i

does not.

**Comment by Araq** [comment]
The example is 

```nim

# Give it a different name to avoid conflict
iterator `...`*[T](a: T, b: T): T =
  var res: T = T(a)
  while res <= b:
    yield res
    inc res

for i in 0...5:
  echo i
```

which is correct, it shows how a ".."-like iterator can be defined.
